/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Usuario
 */
public class CadastroFunc extends javax.swing.JFrame {

    /**
     * Creates new form telaCadastroFuncionario
     */
    public CadastroFunc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulocadstrocliente = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        nome = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        CPF = new javax.swing.JLabel();
        campoCPF = new javax.swing.JTextField();
        datadenascimento = new javax.swing.JLabel();
        campoDataNascimento = new javax.swing.JTextField();
        telefone = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        genero = new javax.swing.JLabel();
        campoGenero = new javax.swing.JComboBox<>();
        endereco = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        Cep = new javax.swing.JLabel();
        campoCep = new javax.swing.JTextField();
        Complemento = new javax.swing.JLabel();
        campoComplemento = new javax.swing.JTextField();
        niveldeacesso = new javax.swing.JLabel();
        campoNiveldeAcesso = new javax.swing.JComboBox<>();
        Senha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JTextField();
        botaoCadastrar = new javax.swing.JButton();
        telafundofuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulocadstrocliente.setBackground(new java.awt.Color(255, 255, 255));
        titulocadstrocliente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titulocadstrocliente.setForeground(new java.awt.Color(255, 255, 255));
        titulocadstrocliente.setText("Cadastro de Funcionario");
        getContentPane().add(titulocadstrocliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 290, 40));

        separador.setForeground(new java.awt.Color(255, 255, 255));
        separador.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        getContentPane().add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 620, 10));

        nome.setForeground(new java.awt.Color(255, 255, 255));
        nome.setText("Nome Completo:");
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 470, -1));
        getContentPane().add(campoNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 560, 30));

        CPF.setForeground(new java.awt.Color(255, 255, 255));
        CPF.setText("CPF:");
        getContentPane().add(CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        getContentPane().add(campoCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, 30));

        datadenascimento.setForeground(new java.awt.Color(255, 255, 255));
        datadenascimento.setText("Data de Nascimento:");
        getContentPane().add(datadenascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, -1, -1));
        getContentPane().add(campoDataNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 160, 30));

        telefone.setForeground(new java.awt.Color(255, 255, 255));
        telefone.setText("Telefone:");
        getContentPane().add(telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        campoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneActionPerformed(evt);
            }
        });
        getContentPane().add(campoTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 160, 30));

        email.setForeground(new java.awt.Color(255, 255, 255));
        email.setText("E-mail:");
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));
        getContentPane().add(campoEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 160, 30));

        genero.setForeground(new java.awt.Color(255, 255, 255));
        genero.setText("Gênero");
        getContentPane().add(genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 50, 10));

        campoGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        campoGenero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                campoGeneroItemStateChanged(evt);
            }
        });
        getContentPane().add(campoGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 160, 30));

        endereco.setForeground(new java.awt.Color(255, 255, 255));
        endereco.setText("Endereço:");
        getContentPane().add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));
        getContentPane().add(campoEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 160, 30));

        Cep.setForeground(new java.awt.Color(255, 255, 255));
        Cep.setText("CEP:");
        getContentPane().add(Cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));
        getContentPane().add(campoCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 160, 30));

        Complemento.setForeground(new java.awt.Color(255, 255, 255));
        Complemento.setText("Complemento:");
        getContentPane().add(Complemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, -1, -1));
        getContentPane().add(campoComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 160, 30));

        niveldeacesso.setForeground(new java.awt.Color(255, 255, 255));
        niveldeacesso.setText("Acesso:");
        getContentPane().add(niveldeacesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        campoNiveldeAcesso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(campoNiveldeAcesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 160, 30));

        Senha.setForeground(new java.awt.Color(255, 255, 255));
        Senha.setText("Senha:");
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(campoSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 160, 30));

        botaoCadastrar.setBackground(new java.awt.Color(0, 255, 0));
        botaoCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 290, 50));

        telafundofuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/viewimagens/background cadastros.jpg"))); // NOI18N
        getContentPane().add(telafundofuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefoneActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void campoGeneroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_campoGeneroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_campoGeneroItemStateChanged

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Cep;
    private javax.swing.JLabel Complemento;
    private javax.swing.JLabel Senha;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JTextField campoCPF;
    private javax.swing.JTextField campoCep;
    private javax.swing.JTextField campoComplemento;
    private javax.swing.JTextField campoDataNascimento;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JComboBox<String> campoGenero;
    private javax.swing.JComboBox<String> campoNiveldeAcesso;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JLabel datadenascimento;
    private javax.swing.JLabel email;
    private javax.swing.JLabel endereco;
    private javax.swing.JLabel genero;
    private javax.swing.JLabel niveldeacesso;
    private javax.swing.JLabel nome;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel telafundofuncionario;
    private javax.swing.JLabel telefone;
    private javax.swing.JLabel titulocadstrocliente;
    // End of variables declaration//GEN-END:variables
}
